# Generated by Django 5.0.4 on 2024-05-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBdCjb_D9bJ_4_LV04BCn7mLHzwimVycKFsQ&s', max_length=500),
        ),
    ]
